/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package muveletek;

/**
 *
 * @author kisba
 */
public class muveletek extends javax.swing.JFrame {

    /**
     * Creates new form muveletek
     */
    public muveletek() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        btnUjKerdes = new javax.swing.JButton();
        btnMegoldas = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtOsszKerd = new javax.swing.JLabel();
        txdOsszeadKerd = new javax.swing.JLabel();
        txtKivonasKerd = new javax.swing.JLabel();
        txtSzorzasKerd = new javax.swing.JLabel();
        txtOsztasKerd = new javax.swing.JLabel();
        txtOsztasProba = new javax.swing.JLabel();
        txtSzorzasProba = new javax.swing.JLabel();
        txtKivonProba = new javax.swing.JLabel();
        txtOsszeadProba = new javax.swing.JLabel();
        txtOsszProba = new javax.swing.JLabel();
        txtEredmény = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtValasz = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtFeladat = new javax.swing.JLabel();
        eredmeny = new javax.swing.JTextField();
        btnEllenorzes = new javax.swing.JButton();
        txtStart = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuFajl = new javax.swing.JMenu();
        menuMegnyit = new javax.swing.JMenuItem();
        menuMent = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuKilep = new javax.swing.JMenuItem();
        menuMuveletek = new javax.swing.JMenu();
        menuOsszead = new javax.swing.JRadioButtonMenuItem();
        menuKivon = new javax.swing.JRadioButtonMenuItem();
        menuSzorzas = new javax.swing.JRadioButtonMenuItem();
        menuOsztas = new javax.swing.JRadioButtonMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnUjKerdes.setText("Új kérdés");
        btnUjKerdes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUjKerdesActionPerformed(evt);
            }
        });

        btnMegoldas.setText("Megoldás");
        btnMegoldas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMegoldasActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setText("Statisztikák");

        txtOsszKerd.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtOsszKerd.setText("Össz kérdések szám: 1");

        txdOsszeadKerd.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txdOsszeadKerd.setText("Összeadás: 1");

        txtKivonasKerd.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtKivonasKerd.setText("Kivonás: 0");

        txtSzorzasKerd.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtSzorzasKerd.setText("Szorzás: 0");

        txtOsztasKerd.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtOsztasKerd.setText("Osztás: 0");

        txtOsztasProba.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtOsztasProba.setText("Osztás: 0");

        txtSzorzasProba.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtSzorzasProba.setText("Szorzás: 0");

        txtKivonProba.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtKivonProba.setText("Kivonás: 0");

        txtOsszeadProba.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtOsszeadProba.setText("Összeadás: 1");

        txtOsszProba.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtOsszProba.setText("Össz próbálkozások száma: 1");

        txtEredmény.setText("Eredmény: 0 %");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txdOsszeadKerd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtOsszKerd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtKivonasKerd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtSzorzasKerd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtOsztasKerd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtOsszeadProba, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtOsszProba, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtKivonProba, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtSzorzasProba, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtOsztasProba, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtEredmény, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtOsszKerd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txdOsszeadKerd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtKivonasKerd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSzorzasKerd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtOsztasKerd))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtOsszProba)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtOsszeadProba)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtKivonProba)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSzorzasProba)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtOsztasProba)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(txtEredmény)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtValasz.setText("15 nem jó!");

        jLabel15.setText("Gyakorlás");

        txtFeladat.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        btnEllenorzes.setText("Ellenőrzés");
        btnEllenorzes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEllenorzesActionPerformed(evt);
            }
        });

        txtStart.setText("Kezdéshez: Műveletek (Válassz) és Új kérdés gomb!");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtStart))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(txtValasz))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtFeladat, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(eredmeny, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEllenorzes)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(txtStart)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFeladat)
                    .addComponent(eredmeny, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEllenorzes))
                .addGap(18, 18, 18)
                .addComponent(txtValasz)
                .addContainerGap())
        );

        menuFajl.setText("File");

        menuMegnyit.setText("Megnyit");
        menuFajl.add(menuMegnyit);

        menuMent.setText("Ment");
        menuFajl.add(menuMent);
        menuFajl.add(jSeparator1);

        menuKilep.setText("Kilép");
        menuFajl.add(menuKilep);

        jMenuBar1.add(menuFajl);

        menuMuveletek.setText("Műveletek");

        buttonGroup1.add(menuOsszead);
        menuOsszead.setText("Összeadás");
        menuMuveletek.add(menuOsszead);

        buttonGroup1.add(menuKivon);
        menuKivon.setText("Kivonás");
        menuMuveletek.add(menuKivon);

        buttonGroup1.add(menuSzorzas);
        menuSzorzas.setText("Szorzás");
        menuMuveletek.add(menuSzorzas);

        buttonGroup1.add(menuOsztas);
        menuOsztas.setSelected(true);
        menuOsztas.setText("Osztás");
        menuMuveletek.add(menuOsztas);

        jMenuBar1.add(menuMuveletek);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnUjKerdes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnMegoldas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnUjKerdes)
                        .addGap(59, 59, 59)
                        .addComponent(btnMegoldas))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
int megoldas=0;
    private void btnUjKerdesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUjKerdesActionPerformed
        if (menuOsztas.isSelected()){
            txtFeladat.setText("6 : 3 =");
            megoldas=(6/3);
            btnEllenorzes.setEnabled(true);
            eredmeny.setEnabled(true);
            txtStart.setText("");
        }
    }//GEN-LAST:event_btnUjKerdesActionPerformed

    private void btnEllenorzesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEllenorzesActionPerformed
        int eredmenyint=Integer.parseInt(eredmeny.getText()); 
        if (megoldas==eredmenyint){
            txtValasz.setText(eredmenyint + " - Helyes válasz!");
            btnEllenorzes.setEnabled(false);
            eredmeny.setEnabled(false);
        }
        else {
            txtValasz.setText(eredmenyint + " - Rossz válasz!");
            eredmeny.setText("");
        }
    }//GEN-LAST:event_btnEllenorzesActionPerformed

    private void btnMegoldasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMegoldasActionPerformed
        txtValasz.setText(megoldas + " volt a helyes válasz!");
        btnEllenorzes.setEnabled(false);
        eredmeny.setEnabled(false);
    }//GEN-LAST:event_btnMegoldasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(muveletek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(muveletek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(muveletek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(muveletek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new muveletek().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEllenorzes;
    private javax.swing.JButton btnMegoldas;
    private javax.swing.JButton btnUjKerdes;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField eredmeny;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenu menuFajl;
    private javax.swing.JMenuItem menuKilep;
    private javax.swing.JRadioButtonMenuItem menuKivon;
    private javax.swing.JMenuItem menuMegnyit;
    private javax.swing.JMenuItem menuMent;
    private javax.swing.JMenu menuMuveletek;
    private javax.swing.JRadioButtonMenuItem menuOsszead;
    private javax.swing.JRadioButtonMenuItem menuOsztas;
    private javax.swing.JRadioButtonMenuItem menuSzorzas;
    private javax.swing.JLabel txdOsszeadKerd;
    private javax.swing.JLabel txtEredmény;
    private javax.swing.JLabel txtFeladat;
    private javax.swing.JLabel txtKivonProba;
    private javax.swing.JLabel txtKivonasKerd;
    private javax.swing.JLabel txtOsszKerd;
    private javax.swing.JLabel txtOsszProba;
    private javax.swing.JLabel txtOsszeadProba;
    private javax.swing.JLabel txtOsztasKerd;
    private javax.swing.JLabel txtOsztasProba;
    private javax.swing.JLabel txtStart;
    private javax.swing.JLabel txtSzorzasKerd;
    private javax.swing.JLabel txtSzorzasProba;
    private javax.swing.JLabel txtValasz;
    // End of variables declaration//GEN-END:variables
}
